// client-react/src/pages/JoinRoom.tsx
import * as React from "react";
import {useState} from "react";
import {useNavigate} from "react-router-dom";
import socket from "../socket.ts";
import {randomNameGenerator} from "../ts/generators.ts";

export const JoinRoom: React.FC = () => {
    const [roomId, setRoomId] = useState('');
    const [name, setName] = useState('');
    const navigate = useNavigate();

    const joinRoom = ()=> {
        if (!roomId) return alert('Please enter a room id');
        if (!name) return alert('Please enter your name');
        socket.emit('joinRoom', { roomId, user: name });

        navigate(`/room/${roomId}`, { state: {name} })
    };

    const createRoom = () => {
        if (!name) return alert('Please enter your name');
        const id = randomNameGenerator();
        setRoomId(id);

        socket.emit('joinRoom', { roomId: id, user: name });
        navigate(`/room/${id}`, { state: { name } });
    };

    return (
        <section>
            <h1>Join a room</h1>
            <input value={roomId}
                   onChange={e => setRoomId(e.target.value)}
                   placeholder="Room ID/Name"
            />
            <input value={name}
                   onChange={e => setName(e.target.value)}
                   placeholder="Name"
            />
            <button onClick={joinRoom}>Join</button>
            <button onClick={createRoom}>Create Room</button>
        </section>
    )
}

// client/src/components/JoinRoom.vue
<template>
  <div v-if="!joined" class="max-w-40px m-auto pt-100px text-center">
    <h1>Join a Room</h1>
    <input
        class="block my-2.5 mx-auto px-4 py-2"
        v-model="roomId"
        placeholder="Room ID"
    />
    <input class="block my-2.5 mx-auto px-4 py-2"
           v-model="name"
           placeholder="Username"
    />
    <button class="m-2 px-5 py-2 text-white border-none rounded cursor-pointer hover:bg-[#cccdcf6e]"
    @click="joinRoom"
    >Join</button>
    <button class="m-2 px-5 py-2 text-white border-none rounded cursor-pointer hover:bg-[#cccdcf6e]"
    @click="createRoom"
    >Create Room
    </button>
  </div>

  <div v-else>
    <Room :room-id="roomId" :name="name" :players="players"/>  
  </div>
</template>

<script setup>
import { ref } from 'vue';
import socket from '../../socket.js'; 
import Room from './Room.vue';
import '../css/join-room.css';

const joined = ref(false);
const name = ref('');
const roomId = ref('');
const players = ref({});

socket.on('connect', () => {
  console.log('Connected to server');
});

const joinRoom = () => {
  if(!name.value || !roomId.value) {
    alert("Please enter a room ID and your name"); return;
  }
  socket.emit('joinRoom', { roomId: roomId.value, user: name.value });
  
  joined.value = true;
  console.log('Joining room:', roomId.value, 'as', name.value);
}

const createRoom = () => {
  if(!name.value) { 
    alert("Please enter your name"); return;
  }
  roomId.value = Math.random().toString(36).substring(2, 6).toUpperCase();

  socket.emit('joinRoom', { roomId: roomId.value, user: name.value });
  
  joined.value = true;
}

socket.on('updateRoom', (data) => {
  players.value = data;
  console.log('Local players now:', players.value);
});


</script>
